### ISSUE TITLE
Reported notes jumping or some slight sync issues?

### ISSUE THREAD

**Issue by ngokevin** [supermedium/beatsaver-viewer#11]
From BennyDaBeast:

> Heyo! Was listening to a song in the Beat Saber viewer, and noticed that there's an odd syncing issue. Sometimes with double notes (a beat that uses both hands), the notes will be slightly off and I'll hear two distinct hits. Happened when I was listening to Some Nights by Fun. Sometimes when I watch closely I'll even see them jump a little, especially when other notes get hit. The closest notes get hit, and I'll see the notes down the track jump. Hope this helps!

**Comment by Sigi-cz** [comment]
same issue here. If i rotate the camera to look from the side I can see the notes are shifted but they are not in the song json data.

**Comment by ngokevin** [comment]
Fixed! https://github.com/supermedium/beatsaver-viewer/commit/6cdc3bf7ebebe02c8f5b36b560ad053b3b34f406
