### ISSUE TITLE
Allow skipping forward/back when the song is stopped

### ISSUE THREAD

**Issue by n3tman** [supermedium/beatsaver-viewer#17]
Currently when you click anywhere on the seekbar when the song is not playing, an exception is displayed in the console:
```
build.js:145 Uncaught DOMException: Failed to execute 'stop' on 'AudioScheduledSourceNode': cannot call stop without calling start first.
```

**Comment by ngokevin** [comment]
Fixed, thanks! https://github.com/supermedium/beatsaver-viewer/commit/552917044d472290f202e92dfd489362a87c27a7
