### ISSUE TITLE
Display song duration and current time position

### ISSUE THREAD

**Issue by n3tman** [supermedium/beatsaver-viewer#18]
Would be great to display track's time information, e.g. YouTube-style:

- duration (mm:ss)
- current position (while playing)
- tooltip on hovering over the seekbar (skip time)

**Comment by ngokevin** [comment]
Added time position / duration. https://github.com/supermedium/beatsaver-viewer/commit/37d6bfb6687a77027cb86c591f43babc9e4a49b2

Will add tooltip hover later.

**Comment by ngokevin** [comment]
https://github.com/supermedium/beatsaver-viewer/commit/a40b5389e3d22ee7f70c94f1d92831443d690830
