### ISSUE TITLE
Add support for "&time=" URL parameter to open a map at specified time

### ISSUE THREAD

**Issue by n3tman** [supermedium/beatsaver-viewer#19]
It would be super helpful to be able to create a link which opens a song at a given position.
Mostly for doing beatmap reviews - pointing people to specified pattern or showing them their mistakes.
Would be similar to `&difficulty=ExpertPlus`

Example - open a map at 3:40 position:

`https://supermedium.com/beatsaver-viewer/?id=11645-12388&time=220`

Also add a link: Copy map URL at current time

**Comment by ngokevin** [comment]
Thanks for filing all the issues, they are all legit.

**Comment by n3tman** [comment]
No worries, hope I don't ask for a lot. I would help myself if I knew Node.js better (and if you accept pull requests, of course).

Thanks so much for this amazing tool!

**Comment by ngokevin** [comment]
Yeah, pull requests accepted, also just plain JavaScript, not Node. But no worries!

**Comment by ngokevin** [comment]
Done! https://github.com/supermedium/beatsaver-viewer/commit/8187bad9ad297092bee0062eb8282af29d560b49
