### ISSUE TITLE
Wall display issue

### ISSUE THREAD

**Issue by LittleAsi** [supermedium/beatsaver-viewer#20]
All the walls in D.A.N.C.E. are vertical, but they all show as Horizontal: https://bsaber.com/songs/11661/

Check 1:51 for example.

They are only on the top two lanes, despite being small in width; the previewer may be seeing that there's nothing walling off the bottom row and assuming it's a full top block from that. Just a theory...

**Comment by ngokevin** [comment]
Thanks. We've been interpreting `wallInfo._type: 1` as a "ceiling", but that's incorrect it seems.

**Comment by ngokevin** [comment]
I've fixed the walls!
