### ISSUE TITLE
The current color scheme is not colorblind friendly

### ISSUE THREAD

**Issue by megalon** [supermedium/beatsaver-viewer#21]
With the current Red / Green color scheme, it is very difficult for red/green colorblind users to distinguish between the different colored blocks. Red / Green is the most common form of color deficiency.

The issue with Beatsaver Viewer currently is that the shade (brightness and saturation) of red and green used are too similar to each other that they are hard to distinguish. If one was a dark red, and the other a light green, it would be easier to tell them apart, but ideally a different color scheme should be used.

If Red / Blue is not possible, Red / Black or maybe Purple / Yellow would work well. 

**Possible solutions:**
* Let users select from a series of preset colors
* Let users define their own colors
* Apply a filter to shift the hue of everything on screen

Thanks for making this app by the way! It's really awesome and I just want everyone to be able to use it!

**Comment by ngokevin** [comment]
Thanks! We'll figure something out.

**Comment by ngokevin** [comment]
@feiss Is it possible to quickly tweak the colors and still have it look visually good?

**Comment by feiss** [comment]
Current color scheme is inspired in our brand colors. What should we do? change current colors or adding a button for letting users switch to another, color blind safe, scheme? 

But my biggest question is: what color scheme is safe for **all kinds** of color blindness? maybe @megalon knows of some reference I can learn from.

**Comment by ngokevin** [comment]
I've switched to Red / Blue! This should alleviate the most common form of color blindness.

https://github.com/supermedium/beatsaver-viewer/commit/c55a8bf57b638b3b76038217fda699455e94011d
