### ISSUE TITLE
Resume after pause causes out of sync / cluttered blocks

### ISSUE THREAD

**Issue by n3tman** [supermedium/beatsaver-viewer#22]
After latest update that made Resume button work diffrently from Restart, another issue arose:

Video: https://take.ms/ijFsk

Issue: When you pause the song, wait for a bit, then resume it, the blocks start flying out of sync / become cluttered.

**Comment by RavenMac** [comment]
I've noticed this as well. I think it's pausing the song, but not the block playback. Using CORS header on a zip from a discord server. Not sure if that has anything to do with the issue though. Also noticed after a long pause that it said the song was playing at 8 minutes on a 5 minute song.

**Comment by ngokevin** [comment]
fixed!
