### ISSUE TITLE
Beatsaver viewer thinks chrome is safari/ios

### ISSUE THREAD

**Issue by Edwin-Baranov** [supermedium/beatsaver-viewer#25]
So this is the first time I'm using your viewer and any song I open on bsaber.com or even your Click To View button on the main GitHub screen shows me the beat saber map with a sign that says ios and safari support coming soon! we need to convert songs to mp3 firs. I am using the Chrome Browser Version 72.0.3626.109 (Official Build) (64-bit)

**Comment by ngokevin** [comment]
Fixed, sorry! https://github.com/supermedium/beatsaver-viewer/commit/7d4c61c0277e9696237600524ae14e9798d2ee6d
