### ISSUE TITLE
Difficulty URL parameter isn't working

### ISSUE THREAD

**Issue by n3tman** [supermedium/beatsaver-viewer#29]
Example map from readme:

https://supermedium.com/beatsaver-viewer/?id=811-535&difficulty=Easy
https://supermedium.com/beatsaver-viewer/?id=811-535&difficulty=Normal
https://supermedium.com/beatsaver-viewer/?id=811-535&difficulty=Hard

All links lead to Expert difficulty being selected.

**Comment by ngokevin** [comment]
Fixed, thanks!

https://github.com/supermedium/beatsaver-viewer/commit/f71705ec0d52dcffff255649bcdf00491c266202
