### ISSUE TITLE
Support new BeatSaver API

### ISSUE THREAD

**Issue by n3tman** [supermedium/beatsaver-viewer#31]
It's probably too early to ask for this, but would be great if this awesome tool supports new BeatSaver rewrite https://beatsaver.com/

Changes include new map format and IDs (alphanumeric).

Repository: https://github.com/lolPants/beatsaver-reloaded

**Comment by ngokevin** [comment]
Thanks for filing! Does the new BeatSaver still support the old formats? Or just completely breaking?

**Comment by n3tman** [comment]
Unfortunately it does not. All maps have been converted to the new format on BeatSaver and it also happens with local maps when you start the latest game version (1.1.0) with latest mods.

There are also manual converters: 
https://raftario.github.io/songe-converter-web/
https://github.com/lolPants/songe-converter

Since new BeatSaver isn't finished yet, you can look at new API format e.g. here: https://beatsaver.com/beatmap/52d3 (it'll be documented later)

**Comment by ngokevin** [comment]
Thanks, I will try to migrate.

**Comment by ngokevin** [comment]
Blocked on https://github.com/lolPants/beatsaver-reloaded/issues/7

**Comment by ngokevin** [comment]
https://github.com/lolPants/beatsaver-reloaded/issues/8

**Comment by ngokevin** [comment]
Done!
