### ISSUE TITLE
Difficulty stays on lowest setting

### ISSUE THREAD

**Issue by Bacon-Kevin** [supermedium/beatsaver-viewer#33]
When I preview a map on bsaber.com, the map difficulty doesn't change from the lowest difficulty even if I manually select harder ones. The same thing happens when I view the map on supermedium.com.

**Comment by ngokevin** [comment]
https://github.com/supermedium/beatsaver-viewer/commit/8f92136d059755ad5f7dfab54451e67ce8337608
