### ISSUE TITLE
The VR mode should be optional (breaks Chrome and is annoying)

### ISSUE THREAD

**Issue by rebane2001** [supermedium/beatsaver-viewer#35]
The new VR mode that was added at some point launches SteamVR every time I try to preview a song in Firefox, which is annoying. In Chrome, the viewer doesn't load at all and throws a bunch of JS errors. It used to work in Chrome just fine.  
I think the VR mode should be a separate button that needs to be pressed for it to activate

**Comment by ngokevin** [comment]
Thanks, I will work on this now. This is a symptom of browsers auto-booting Steam when JS asks for anything VR related.

**Comment by ngokevin** [comment]
No longer launches SteamVR and fixed in Chrome!
