### ISSUE TITLE
Bringing awareness to a collection of issues

### ISSUE THREAD

**Issue by megalon** [supermedium/beatsaver-viewer#36]
Hello, this is Megalon from the Beat Saber Modding Group Discord.
I've recently learned that the mapping community within our Discord server has several complaints about the beatsaver-viewer, and have started building their own tool as a replacement.
However, most of the issues don't appear to be listed here in the issues for this repo, so I've posted them below.

```
1. No audio plays and no notes appear when specifying a zip file
2. Skips notes if too many appear in the song
3. VR starts randomly
4. No mapping extensions support, causes walls to stretch across the entire screen
5. NJS is not calculated properly, makes high NPS maps unreadable
6. Can’t view any game modes besides standard
7. Can’t see custom difficulty labels
8. Walls are buggy in general
```
The above text was taken directly from a message by `Rabbit#0001`, the developer of the new tool that is being built.

Are you aware of these issues?

**Comment by ngokevin** [comment]
Thanks for bringing to our attention. I am not sure we have bandwidth to maintain the viewer especially as maps evolve. I'm glad your team is working on a new tool and looking forward to it. You are free to use any assets we've created here, and are open to any pull requests!

**Comment by ngokevin** [comment]
Hey @megalon, I am freed up so I will be looking into these issues now.

**Comment by ngokevin** [comment]
Starting to knock them down. I added drag/drop ZIP.

- [x] No audio plays and no notes appear when specifying a zip file
- [x] Skips notes if too many appear in the song
- [x] VR starts randomly
- [x] No mapping extensions support, causes walls to stretch across the entire screen
- [x] NJS is not calculated properly, makes high NPS maps unreadable
- [ ] Can’t view any game modes besides standard
- [x] Can’t see custom difficulty labels
- [x] Walls are buggy in general

**Comment by ngokevin** [comment]
(nevermind, i had commented for info here before but i fixed most issues and found info myself)

**Comment by ngokevin** [comment]
I've factored in custom NJS, fixed the walls.

**Comment by ngokevin** [comment]
added mapping extension support for notes

**Comment by ngokevin** [comment]
added mapping extension support for walls

**Comment by ngokevin** [comment]
@megalon I've fixed everything except custom modes besides Standards and added some new features. Let me know how it is.
