### ISSUE TITLE
"Ear rape" when switching Difficulty

### ISSUE THREAD

**Issue by n3tman** [supermedium/beatsaver-viewer#5]
Not sure if this was intentional or not, but when you change difficulty e.g. from ExpertPlus to Expert, it looks like hundred "collision sounds" are played simultaneously, thus causing a loud noise.

Edit: same happens when you click anywhere on the timeline (skipping also doesn't work).

Example songs: 
https://supermedium.com/beatsaver-viewer/?id=4412-3669
https://supermedium.com/beatsaver-viewer/?id=517-321

Browser: Google Chrome, version 71.0.3578.98 (Official Build) (64-bit)
OS: Windows 10 Pro 64bit, build 1809

Made me flinch the first time it happened, lol.

**Comment by ngokevin** [comment]
Fixed. Thanks for reporting!
