### ISSUE TITLE
Display an error if a song can't be fetched (e.g. if .zip is not found)

### ISSUE THREAD

**Issue by n3tman** [supermedium/beatsaver-viewer#8]
Currently there's no indication if a song can't be found on Beatsaver website.

Message says "Downloading song...", example: https://supermedium.com/beatsaver-viewer/?id=811-533

Would be nice to implement a callback and change the message accordingly (like "Song can't be found").

**Comment by ngokevin** [comment]
Alright, working on it.

**Comment by ngokevin** [comment]
https://github.com/supermedium/beatsaver-viewer/commit/ca8245c7bc0251c859429a12f627f2b1d2013484
